### ISSUE TITLE
Doesn't work for baritone support on the modpack MC Eternal

### ISSUE THREAD

**Issue by Niceghost21** [NotStirred/MixinCompat#3]
[latest.log](https://github.com/NotStirred/MixinCompat/files/6053730/latest.log)
^ Thats my log of loading this compatibility mod, with baritone, in the MC Eternal modpack.  Baritone uses 0.7.11 and the mod bewitchment uses 0.8, so I thought this mod would get rid of the problem, but it seems like a new problem arose.  Please could you look at my log and tell me if I can do anything to solve this problem?  Also, below this is another log, this time for running the game without the compatibility mod, just with baritone and the modpack, if that helps at all.
[latest.log](https://github.com/NotStirred/MixinCompat/files/6053735/latest.log)

**Comment by Niceghost21** [comment]
Also, the compatibility mod works fine in the modpack without baritone of course, its just not being used I'm assuming.  Didn't know if that bit of knowledge would help at all

**Comment by Niceghost21** [comment]
Here is the baritone mod i am using that is causing this error.
[baritone.zip](https://github.com/NotStirred/MixinCompat/files/6053752/baritone.zip)

**Comment by NotStirred** [comment]
looks like some other mod is doing something stupid and classloading `GuiScreen` too early, possibly in some transformer somewhere?
Not anything I can do to fix that sadly, you'd need to check every mod in the modpack for this :/
